// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.0
// Schema file: dune.xsd
// Creation Date: 2007-11-06 17:11:45
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace YAD2Configuration
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://www.example.org/dune";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class AmmoDataCollection : ArrayList
	{
		public YAD2Configuration.AmmoData Add(YAD2Configuration.AmmoData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.AmmoData Add()
		{
			return Add(new YAD2Configuration.AmmoData());
		}

		public void Insert(int index, YAD2Configuration.AmmoData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.AmmoData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.AmmoData this[int index]
		{
			get { return (YAD2Configuration.AmmoData) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class TechnologyDependenceCollection : ArrayList
	{
		public YAD2Configuration.TechnologyDependence Add(YAD2Configuration.TechnologyDependence obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.TechnologyDependence Add()
		{
			return Add(new YAD2Configuration.TechnologyDependence());
		}

		public void Insert(int index, YAD2Configuration.TechnologyDependence obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.TechnologyDependence obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.TechnologyDependence this[int index]
		{
			get { return (YAD2Configuration.TechnologyDependence) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class RaceDataCollection : ArrayList
	{
		public YAD2Configuration.RaceData Add(YAD2Configuration.RaceData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.RaceData Add()
		{
			return Add(new YAD2Configuration.RaceData());
		}

		public void Insert(int index, YAD2Configuration.RaceData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.RaceData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.RaceData this[int index]
		{
			get { return (YAD2Configuration.RaceData) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class NameCollection : ArrayList
	{
		public string Add(string obj)
		{
			base.Add(obj);
			return obj;
		}

		public void Insert(int index, string obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(string obj)
		{
			base.Remove(obj);
		}

		new public string this[int index]
		{
			get { return (string) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitMCVDataCollection : ArrayList
	{
		public YAD2Configuration.UnitMCVData Add(YAD2Configuration.UnitMCVData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.UnitMCVData Add()
		{
			return Add(new YAD2Configuration.UnitMCVData());
		}

		public void Insert(int index, YAD2Configuration.UnitMCVData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.UnitMCVData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.UnitMCVData this[int index]
		{
			get { return (YAD2Configuration.UnitMCVData) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class indexCollection : ArrayList
	{
		public int Add(int obj)
		{
			base.Add(obj);
			return obj;
		}

		public int Add()
		{
			return Add(new int());
		}

		public void Insert(int index, int obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(int obj)
		{
			base.Remove(obj);
		}

		new public int this[int index]
		{
			get { return (int) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class BuildingsNamesCollection : ArrayList
	{
		public YAD2Configuration.BuildingsNames Add(YAD2Configuration.BuildingsNames obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.BuildingsNames Add()
		{
			return Add(new YAD2Configuration.BuildingsNames());
		}

		public void Insert(int index, YAD2Configuration.BuildingsNames obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.BuildingsNames obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.BuildingsNames this[int index]
		{
			get { return (YAD2Configuration.BuildingsNames) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitSandwormDataCollection : ArrayList
	{
		public YAD2Configuration.UnitSandwormData Add(YAD2Configuration.UnitSandwormData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.UnitSandwormData Add()
		{
			return Add(new YAD2Configuration.UnitSandwormData());
		}

		public void Insert(int index, YAD2Configuration.UnitSandwormData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.UnitSandwormData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.UnitSandwormData this[int index]
		{
			get { return (YAD2Configuration.UnitSandwormData) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class BuildingNameCollection : ArrayList
	{
		public string Add(string obj)
		{
			base.Add(obj);
			return obj;
		}

		public void Insert(int index, string obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(string obj)
		{
			base.Remove(obj);
		}

		new public string this[int index]
		{
			get { return (string) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitHarvesterDataCollection : ArrayList
	{
		public YAD2Configuration.UnitHarvesterData Add(YAD2Configuration.UnitHarvesterData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.UnitHarvesterData Add()
		{
			return Add(new YAD2Configuration.UnitHarvesterData());
		}

		public void Insert(int index, YAD2Configuration.UnitHarvesterData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.UnitHarvesterData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.UnitHarvesterData this[int index]
		{
			get { return (YAD2Configuration.UnitHarvesterData) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitTrooperDataCollection : ArrayList
	{
		public YAD2Configuration.UnitTrooperData Add(YAD2Configuration.UnitTrooperData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.UnitTrooperData Add()
		{
			return Add(new YAD2Configuration.UnitTrooperData());
		}

		public void Insert(int index, YAD2Configuration.UnitTrooperData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.UnitTrooperData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.UnitTrooperData this[int index]
		{
			get { return (YAD2Configuration.UnitTrooperData) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class BuildingDataCollection : ArrayList
	{
		public YAD2Configuration.BuildingData Add(YAD2Configuration.BuildingData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.BuildingData Add()
		{
			return Add(new YAD2Configuration.BuildingData());
		}

		public void Insert(int index, YAD2Configuration.BuildingData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.BuildingData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.BuildingData this[int index]
		{
			get { return (YAD2Configuration.BuildingData) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitTankDataCollection : ArrayList
	{
		public YAD2Configuration.UnitTankData Add(YAD2Configuration.UnitTankData obj)
		{
			base.Add(obj);
			return obj;
		}

		public YAD2Configuration.UnitTankData Add()
		{
			return Add(new YAD2Configuration.UnitTankData());
		}

		public void Insert(int index, YAD2Configuration.UnitTankData obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(YAD2Configuration.UnitTankData obj)
		{
			base.Remove(obj);
		}

		new public YAD2Configuration.UnitTankData this[int index]
		{
			get { return (YAD2Configuration.UnitTankData) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlType(TypeName="UnitTrooperData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitTrooperData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Cost",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Cost;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __CostSpecified;
		
		[XmlIgnore]
		public int Cost
		{ 
			get { return __Cost; }
			set { __Cost = value; __CostSpecified = true; }
		}

		[XmlElement(ElementName="FireRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __FireRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __FireRangeSpecified;
		
		[XmlIgnore]
		public int FireRange
		{ 
			get { return __FireRange; }
			set { __FireRange = value; __FireRangeSpecified = true; }
		}

		[XmlElement(ElementName="Speed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Speed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SpeedSpecified;
		
		[XmlIgnore]
		public int Speed
		{ 
			get { return __Speed; }
			set { __Speed = value; __SpeedSpecified = true; }
		}

		[XmlElement(ElementName="ReloadTime",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ReloadTime;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ReloadTimeSpecified;
		
		[XmlIgnore]
		public int ReloadTime
		{ 
			get { return __ReloadTime; }
			set { __ReloadTime = value; __ReloadTimeSpecified = true; }
		}

		[XmlElement(ElementName="AmmoType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AmmoType;
		
		[XmlIgnore]
		public string AmmoType
		{ 
			get { return __AmmoType; }
			set { __AmmoType = value; }
		}

		[XmlElement(ElementName="Health",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Health;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HealthSpecified;
		
		[XmlIgnore]
		public int Health
		{ 
			get { return __Health; }
			set { __Health = value; __HealthSpecified = true; }
		}

		[XmlElement(ElementName="ViewRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ViewRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ViewRangeSpecified;
		
		[XmlIgnore]
		public int ViewRange
		{ 
			get { return __ViewRange; }
			set { __ViewRange = value; __ViewRangeSpecified = true; }
		}

		[XmlElement(ElementName="Power",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Power;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PowerSpecified;
		
		[XmlIgnore]
		public int Power
		{ 
			get { return __Power; }
			set { __Power = value; __PowerSpecified = true; }
		}

		[XmlElement(ElementName="BuildSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __BuildSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __BuildSpeedSpecified;
		
		[XmlIgnore]
		public int BuildSpeed
		{ 
			get { return __BuildSpeed; }
			set { __BuildSpeed = value; __BuildSpeedSpecified = true; }
		}

		[XmlElement(ElementName="DamageDestroy",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __DamageDestroy;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DamageDestroySpecified;
		
		[XmlIgnore]
		public int DamageDestroy
		{ 
			get { return __DamageDestroy; }
			set { __DamageDestroy = value; __DamageDestroySpecified = true; }
		}

		[XmlElement(ElementName="RotationSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __RotationSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __RotationSpeedSpecified;
		
		[XmlIgnore]
		public int RotationSpeed
		{ 
			get { return __RotationSpeed; }
			set { __RotationSpeed = value; __RotationSpeedSpecified = true; }
		}

		[XmlElement(ElementName="Texture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Texture;
		
		[XmlIgnore]
		public string Texture
		{ 
			get { return __Texture; }
			set { __Texture = value; }
		}

		[XmlElement(ElementName="Picture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Picture;
		
		[XmlIgnore]
		public string Picture
		{ 
			get { return __Picture; }
			set { __Picture = value; }
		}

		public UnitTrooperData()
		{
		}
	}


	[XmlType(TypeName="UnitTankData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitTankData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Cost",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Cost;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __CostSpecified;
		
		[XmlIgnore]
		public int Cost
		{ 
			get { return __Cost; }
			set { __Cost = value; __CostSpecified = true; }
		}

		[XmlElement(ElementName="FireRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __FireRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __FireRangeSpecified;
		
		[XmlIgnore]
		public int FireRange
		{ 
			get { return __FireRange; }
			set { __FireRange = value; __FireRangeSpecified = true; }
		}

		[XmlElement(ElementName="Speed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Speed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SpeedSpecified;
		
		[XmlIgnore]
		public int Speed
		{ 
			get { return __Speed; }
			set { __Speed = value; __SpeedSpecified = true; }
		}

		[XmlElement(ElementName="ReloadTime",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ReloadTime;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ReloadTimeSpecified;
		
		[XmlIgnore]
		public int ReloadTime
		{ 
			get { return __ReloadTime; }
			set { __ReloadTime = value; __ReloadTimeSpecified = true; }
		}

		[XmlElement(ElementName="AmmoType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AmmoType;
		
		[XmlIgnore]
		public string AmmoType
		{ 
			get { return __AmmoType; }
			set { __AmmoType = value; }
		}

		[XmlElement(ElementName="Health",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Health;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HealthSpecified;
		
		[XmlIgnore]
		public int Health
		{ 
			get { return __Health; }
			set { __Health = value; __HealthSpecified = true; }
		}

		[XmlElement(ElementName="ViewRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ViewRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ViewRangeSpecified;
		
		[XmlIgnore]
		public int ViewRange
		{ 
			get { return __ViewRange; }
			set { __ViewRange = value; __ViewRangeSpecified = true; }
		}

		[XmlElement(ElementName="Power",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Power;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PowerSpecified;
		
		[XmlIgnore]
		public int Power
		{ 
			get { return __Power; }
			set { __Power = value; __PowerSpecified = true; }
		}

		[XmlElement(ElementName="BuildSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __BuildSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __BuildSpeedSpecified;
		
		[XmlIgnore]
		public int BuildSpeed
		{ 
			get { return __BuildSpeed; }
			set { __BuildSpeed = value; __BuildSpeedSpecified = true; }
		}

		[XmlElement(ElementName="DamageDestroy",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __DamageDestroy;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DamageDestroySpecified;
		
		[XmlIgnore]
		public int DamageDestroy
		{ 
			get { return __DamageDestroy; }
			set { __DamageDestroy = value; __DamageDestroySpecified = true; }
		}

		[XmlElement(ElementName="RotationSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __RotationSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __RotationSpeedSpecified;
		
		[XmlIgnore]
		public int RotationSpeed
		{ 
			get { return __RotationSpeed; }
			set { __RotationSpeed = value; __RotationSpeedSpecified = true; }
		}

		[XmlElement(ElementName="TurretRotationSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __TurretRotationSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __TurretRotationSpeedSpecified;
		
		[XmlIgnore]
		public int TurretRotationSpeed
		{ 
			get { return __TurretRotationSpeed; }
			set { __TurretRotationSpeed = value; __TurretRotationSpeedSpecified = true; }
		}

		[XmlElement(ElementName="TurretTexture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __TurretTexture;
		
		[XmlIgnore]
		public string TurretTexture
		{ 
			get { return __TurretTexture; }
			set { __TurretTexture = value; }
		}

		[XmlElement(ElementName="Texture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Texture;
		
		[XmlIgnore]
		public string Texture
		{ 
			get { return __Texture; }
			set { __Texture = value; }
		}

		[XmlElement(ElementName="Picture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Picture;
		
		[XmlIgnore]
		public string Picture
		{ 
			get { return __Picture; }
			set { __Picture = value; }
		}

		public UnitTankData()
		{
		}
	}


	[XmlType(TypeName="UnitHarvesterData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitHarvesterData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Cost",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Cost;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __CostSpecified;
		
		[XmlIgnore]
		public int Cost
		{ 
			get { return __Cost; }
			set { __Cost = value; __CostSpecified = true; }
		}

		[XmlElement(ElementName="Speed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Speed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SpeedSpecified;
		
		[XmlIgnore]
		public int Speed
		{ 
			get { return __Speed; }
			set { __Speed = value; __SpeedSpecified = true; }
		}

		[XmlElement(ElementName="Health",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Health;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HealthSpecified;
		
		[XmlIgnore]
		public int Health
		{ 
			get { return __Health; }
			set { __Health = value; __HealthSpecified = true; }
		}

		[XmlElement(ElementName="ViewRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ViewRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ViewRangeSpecified;
		
		[XmlIgnore]
		public int ViewRange
		{ 
			get { return __ViewRange; }
			set { __ViewRange = value; __ViewRangeSpecified = true; }
		}

		[XmlElement(ElementName="BuildSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __BuildSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __BuildSpeedSpecified;
		
		[XmlIgnore]
		public int BuildSpeed
		{ 
			get { return __BuildSpeed; }
			set { __BuildSpeed = value; __BuildSpeedSpecified = true; }
		}

		[XmlElement(ElementName="DamageDestroy",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __DamageDestroy;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DamageDestroySpecified;
		
		[XmlIgnore]
		public int DamageDestroy
		{ 
			get { return __DamageDestroy; }
			set { __DamageDestroy = value; __DamageDestroySpecified = true; }
		}

		[XmlElement(ElementName="RotationSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __RotationSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __RotationSpeedSpecified;
		
		[XmlIgnore]
		public int RotationSpeed
		{ 
			get { return __RotationSpeed; }
			set { __RotationSpeed = value; __RotationSpeedSpecified = true; }
		}

		[XmlElement(ElementName="Capacity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Capacity;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __CapacitySpecified;
		
		[XmlIgnore]
		public int Capacity
		{ 
			get { return __Capacity; }
			set { __Capacity = value; __CapacitySpecified = true; }
		}

		[XmlElement(ElementName="GatheringSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __GatheringSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __GatheringSpeedSpecified;
		
		[XmlIgnore]
		public int GatheringSpeed
		{ 
			get { return __GatheringSpeed; }
			set { __GatheringSpeed = value; __GatheringSpeedSpecified = true; }
		}

		[XmlElement(ElementName="Texture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Texture;
		
		[XmlIgnore]
		public string Texture
		{ 
			get { return __Texture; }
			set { __Texture = value; }
		}

		[XmlElement(ElementName="Picture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Picture;
		
		[XmlIgnore]
		public string Picture
		{ 
			get { return __Picture; }
			set { __Picture = value; }
		}

		public UnitHarvesterData()
		{
		}
	}


	[XmlType(TypeName="UnitMCVData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitMCVData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Cost",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Cost;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __CostSpecified;
		
		[XmlIgnore]
		public int Cost
		{ 
			get { return __Cost; }
			set { __Cost = value; __CostSpecified = true; }
		}

		[XmlElement(ElementName="Speed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Speed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SpeedSpecified;
		
		[XmlIgnore]
		public int Speed
		{ 
			get { return __Speed; }
			set { __Speed = value; __SpeedSpecified = true; }
		}

		[XmlElement(ElementName="Health",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Health;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HealthSpecified;
		
		[XmlIgnore]
		public int Health
		{ 
			get { return __Health; }
			set { __Health = value; __HealthSpecified = true; }
		}

		[XmlElement(ElementName="ViewRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ViewRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ViewRangeSpecified;
		
		[XmlIgnore]
		public int ViewRange
		{ 
			get { return __ViewRange; }
			set { __ViewRange = value; __ViewRangeSpecified = true; }
		}

		[XmlElement(ElementName="BuildSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __BuildSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __BuildSpeedSpecified;
		
		[XmlIgnore]
		public int BuildSpeed
		{ 
			get { return __BuildSpeed; }
			set { __BuildSpeed = value; __BuildSpeedSpecified = true; }
		}

		[XmlElement(ElementName="DamageDestroy",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __DamageDestroy;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DamageDestroySpecified;
		
		[XmlIgnore]
		public int DamageDestroy
		{ 
			get { return __DamageDestroy; }
			set { __DamageDestroy = value; __DamageDestroySpecified = true; }
		}

		[XmlElement(ElementName="RotationSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __RotationSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __RotationSpeedSpecified;
		
		[XmlIgnore]
		public int RotationSpeed
		{ 
			get { return __RotationSpeed; }
			set { __RotationSpeed = value; __RotationSpeedSpecified = true; }
		}

		[XmlElement(ElementName="BuildingCanProduce",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BuildingCanProduce;
		
		[XmlIgnore]
		public string BuildingCanProduce
		{ 
			get { return __BuildingCanProduce; }
			set { __BuildingCanProduce = value; }
		}

		[XmlElement(ElementName="Texture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Texture;
		
		[XmlIgnore]
		public string Texture
		{ 
			get { return __Texture; }
			set { __Texture = value; }
		}

		[XmlElement(ElementName="Picture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Picture;
		
		[XmlIgnore]
		public string Picture
		{ 
			get { return __Picture; }
			set { __Picture = value; }
		}

		public UnitMCVData()
		{
		}
	}


	[XmlType(TypeName="UnitSandwormData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitSandwormData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Speed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Speed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SpeedSpecified;
		
		[XmlIgnore]
		public int Speed
		{ 
			get { return __Speed; }
			set { __Speed = value; __SpeedSpecified = true; }
		}

		[XmlElement(ElementName="Health",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Health;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HealthSpecified;
		
		[XmlIgnore]
		public int Health
		{ 
			get { return __Health; }
			set { __Health = value; __HealthSpecified = true; }
		}

		[XmlElement(ElementName="Power",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Power;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PowerSpecified;
		
		[XmlIgnore]
		public int Power
		{ 
			get { return __Power; }
			set { __Power = value; __PowerSpecified = true; }
		}

		[XmlElement(ElementName="DamageDestroy",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __DamageDestroy;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DamageDestroySpecified;
		
		[XmlIgnore]
		public int DamageDestroy
		{ 
			get { return __DamageDestroy; }
			set { __DamageDestroy = value; __DamageDestroySpecified = true; }
		}

		[XmlElement(ElementName="RotationSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __RotationSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __RotationSpeedSpecified;
		
		[XmlIgnore]
		public int RotationSpeed
		{ 
			get { return __RotationSpeed; }
			set { __RotationSpeed = value; __RotationSpeedSpecified = true; }
		}

		[XmlElement(ElementName="Texture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Texture;
		
		[XmlIgnore]
		public string Texture
		{ 
			get { return __Texture; }
			set { __Texture = value; }
		}

		public UnitSandwormData()
		{
		}
	}


	[XmlType(TypeName="BuildingData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class BuildingData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Cost",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Cost;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __CostSpecified;
		
		[XmlIgnore]
		public int Cost
		{ 
			get { return __Cost; }
			set { __Cost = value; __CostSpecified = true; }
		}

		[XmlElement(ElementName="Health",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Health;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HealthSpecified;
		
		[XmlIgnore]
		public int Health
		{ 
			get { return __Health; }
			set { __Health = value; __HealthSpecified = true; }
		}

		[XmlElement(ElementName="ViewRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ViewRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ViewRangeSpecified;
		
		[XmlIgnore]
		public int ViewRange
		{ 
			get { return __ViewRange; }
			set { __ViewRange = value; __ViewRangeSpecified = true; }
		}

		[XmlElement(ElementName="BuildSpeed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __BuildSpeed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __BuildSpeedSpecified;
		
		[XmlIgnore]
		public int BuildSpeed
		{ 
			get { return __BuildSpeed; }
			set { __BuildSpeed = value; __BuildSpeedSpecified = true; }
		}

		[XmlElement(ElementName="Texture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Texture;
		
		[XmlIgnore]
		public string Texture
		{ 
			get { return __Texture; }
			set { __Texture = value; }
		}

		[XmlElement(ElementName="Picture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Picture;
		
		[XmlIgnore]
		public string Picture
		{ 
			get { return __Picture; }
			set { __Picture = value; }
		}

		[XmlElement(Type=typeof(YAD2Configuration.Size),ElementName="Size",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.Size __Size;
		
		[XmlIgnore]
		public YAD2Configuration.Size Size
		{
			get
			{
				if (__Size == null) __Size = new YAD2Configuration.Size();		
				return __Size;
			}
			set {__Size = value;}
		}

		[XmlElement(ElementName="EnergyConsumption",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __EnergyConsumption;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __EnergyConsumptionSpecified;
		
		[XmlIgnore]
		public int EnergyConsumption
		{ 
			get { return __EnergyConsumption; }
			set { __EnergyConsumption = value; __EnergyConsumptionSpecified = true; }
		}

		[XmlElement(Type=typeof(YAD2Configuration.RideableFields),ElementName="RideableFields",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.RideableFields __RideableFields;
		
		[XmlIgnore]
		public YAD2Configuration.RideableFields RideableFields
		{
			get
			{
				if (__RideableFields == null) __RideableFields = new YAD2Configuration.RideableFields();		
				return __RideableFields;
			}
			set {__RideableFields = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.UnitsNames),ElementName="UnitsCanProduce",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.UnitsNames __UnitsCanProduce;
		
		[XmlIgnore]
		public YAD2Configuration.UnitsNames UnitsCanProduce
		{
			get
			{
				if (__UnitsCanProduce == null) __UnitsCanProduce = new YAD2Configuration.UnitsNames();		
				return __UnitsCanProduce;
			}
			set {__UnitsCanProduce = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.BuildingsNames),ElementName="BuildingsCanProduce",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.BuildingsNames __BuildingsCanProduce;
		
		[XmlIgnore]
		public YAD2Configuration.BuildingsNames BuildingsCanProduce
		{
			get
			{
				if (__BuildingsCanProduce == null) __BuildingsCanProduce = new YAD2Configuration.BuildingsNames();		
				return __BuildingsCanProduce;
			}
			set {__BuildingsCanProduce = value;}
		}

		[XmlElement(ElementName="Power",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Power;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PowerSpecified;
		
		[XmlIgnore]
		public int Power
		{ 
			get { return __Power; }
			set { __Power = value; __PowerSpecified = true; }
		}

		[XmlElement(ElementName="FireRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __FireRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __FireRangeSpecified;
		
		[XmlIgnore]
		public int FireRange
		{ 
			get { return __FireRange; }
			set { __FireRange = value; __FireRangeSpecified = true; }
		}

		[XmlElement(ElementName="ReloadTime",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ReloadTime;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ReloadTimeSpecified;
		
		[XmlIgnore]
		public int ReloadTime
		{ 
			get { return __ReloadTime; }
			set { __ReloadTime = value; __ReloadTimeSpecified = true; }
		}

		public BuildingData()
		{
		}
	}


	[XmlType(TypeName="AmmoData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class AmmoData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Speed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Speed;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SpeedSpecified;
		
		[XmlIgnore]
		public int Speed
		{ 
			get { return __Speed; }
			set { __Speed = value; __SpeedSpecified = true; }
		}

		[XmlElement(ElementName="DamageDestroyRange",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __DamageDestroyRange;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DamageDestroyRangeSpecified;
		
		[XmlIgnore]
		public int DamageDestroyRange
		{ 
			get { return __DamageDestroyRange; }
			set { __DamageDestroyRange = value; __DamageDestroyRangeSpecified = true; }
		}

		[XmlElement(ElementName="Texture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Texture;
		
		[XmlIgnore]
		public string Texture
		{ 
			get { return __Texture; }
			set { __Texture = value; }
		}

		public AmmoData()
		{
		}
	}


	[XmlType(TypeName="RaceData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class RaceData
	{

		[XmlElement(ElementName="ID",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __ID;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IDSpecified;
		
		[XmlIgnore]
		public int ID
		{ 
			get { return __ID; }
			set { __ID = value; __IDSpecified = true; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(Type=typeof(YAD2Configuration.TechnologyDependences),ElementName="TechnologyDependences",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.TechnologyDependences __TechnologyDependences;
		
		[XmlIgnore]
		public YAD2Configuration.TechnologyDependences TechnologyDependences
		{
			get
			{
				if (__TechnologyDependences == null) __TechnologyDependences = new YAD2Configuration.TechnologyDependences();		
				return __TechnologyDependences;
			}
			set {__TechnologyDependences = value;}
		}

		public RaceData()
		{
		}
	}


	[XmlType(TypeName="UnitTroopersData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitTroopersData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return UnitTrooperDataCollection.GetEnumerator();
		}

		public YAD2Configuration.UnitTrooperData Add(YAD2Configuration.UnitTrooperData obj)
		{
			return UnitTrooperDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.UnitTrooperData this[int index]
		{
			get { return (YAD2Configuration.UnitTrooperData) UnitTrooperDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return UnitTrooperDataCollection.Count; }
        }

        public void Clear()
		{
			UnitTrooperDataCollection.Clear();
        }

		public YAD2Configuration.UnitTrooperData Remove(int index) 
		{ 
            YAD2Configuration.UnitTrooperData obj = UnitTrooperDataCollection[index];
            UnitTrooperDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            UnitTrooperDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.UnitTrooperData),ElementName="UnitTrooperData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public UnitTrooperDataCollection __UnitTrooperDataCollection;
		
		[XmlIgnore]
		public UnitTrooperDataCollection UnitTrooperDataCollection
		{
			get
			{
				if (__UnitTrooperDataCollection == null) __UnitTrooperDataCollection = new UnitTrooperDataCollection();
				return __UnitTrooperDataCollection;
			}
			set {__UnitTrooperDataCollection = value;}
		}

		public UnitTroopersData()
		{
		}
	}


	[XmlType(TypeName="UnitTanksData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitTanksData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return UnitTankDataCollection.GetEnumerator();
		}

		public YAD2Configuration.UnitTankData Add(YAD2Configuration.UnitTankData obj)
		{
			return UnitTankDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.UnitTankData this[int index]
		{
			get { return (YAD2Configuration.UnitTankData) UnitTankDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return UnitTankDataCollection.Count; }
        }

        public void Clear()
		{
			UnitTankDataCollection.Clear();
        }

		public YAD2Configuration.UnitTankData Remove(int index) 
		{ 
            YAD2Configuration.UnitTankData obj = UnitTankDataCollection[index];
            UnitTankDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            UnitTankDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.UnitTankData),ElementName="UnitTankData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public UnitTankDataCollection __UnitTankDataCollection;
		
		[XmlIgnore]
		public UnitTankDataCollection UnitTankDataCollection
		{
			get
			{
				if (__UnitTankDataCollection == null) __UnitTankDataCollection = new UnitTankDataCollection();
				return __UnitTankDataCollection;
			}
			set {__UnitTankDataCollection = value;}
		}

		public UnitTanksData()
		{
		}
	}


	[XmlType(TypeName="UnitHarvestersData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitHarvestersData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return UnitHarvesterDataCollection.GetEnumerator();
		}

		public YAD2Configuration.UnitHarvesterData Add(YAD2Configuration.UnitHarvesterData obj)
		{
			return UnitHarvesterDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.UnitHarvesterData this[int index]
		{
			get { return (YAD2Configuration.UnitHarvesterData) UnitHarvesterDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return UnitHarvesterDataCollection.Count; }
        }

        public void Clear()
		{
			UnitHarvesterDataCollection.Clear();
        }

		public YAD2Configuration.UnitHarvesterData Remove(int index) 
		{ 
            YAD2Configuration.UnitHarvesterData obj = UnitHarvesterDataCollection[index];
            UnitHarvesterDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            UnitHarvesterDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.UnitHarvesterData),ElementName="UnitHarvesterData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public UnitHarvesterDataCollection __UnitHarvesterDataCollection;
		
		[XmlIgnore]
		public UnitHarvesterDataCollection UnitHarvesterDataCollection
		{
			get
			{
				if (__UnitHarvesterDataCollection == null) __UnitHarvesterDataCollection = new UnitHarvesterDataCollection();
				return __UnitHarvesterDataCollection;
			}
			set {__UnitHarvesterDataCollection = value;}
		}

		public UnitHarvestersData()
		{
		}
	}


	[XmlType(TypeName="UnitMCVsData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitMCVsData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return UnitMCVDataCollection.GetEnumerator();
		}

		public YAD2Configuration.UnitMCVData Add(YAD2Configuration.UnitMCVData obj)
		{
			return UnitMCVDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.UnitMCVData this[int index]
		{
			get { return (YAD2Configuration.UnitMCVData) UnitMCVDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return UnitMCVDataCollection.Count; }
        }

        public void Clear()
		{
			UnitMCVDataCollection.Clear();
        }

		public YAD2Configuration.UnitMCVData Remove(int index) 
		{ 
            YAD2Configuration.UnitMCVData obj = UnitMCVDataCollection[index];
            UnitMCVDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            UnitMCVDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.UnitMCVData),ElementName="UnitMCVData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public UnitMCVDataCollection __UnitMCVDataCollection;
		
		[XmlIgnore]
		public UnitMCVDataCollection UnitMCVDataCollection
		{
			get
			{
				if (__UnitMCVDataCollection == null) __UnitMCVDataCollection = new UnitMCVDataCollection();
				return __UnitMCVDataCollection;
			}
			set {__UnitMCVDataCollection = value;}
		}

		public UnitMCVsData()
		{
		}
	}


	[XmlType(TypeName="UnitSandwormsData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitSandwormsData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return UnitSandwormDataCollection.GetEnumerator();
		}

		public YAD2Configuration.UnitSandwormData Add(YAD2Configuration.UnitSandwormData obj)
		{
			return UnitSandwormDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.UnitSandwormData this[int index]
		{
			get { return (YAD2Configuration.UnitSandwormData) UnitSandwormDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return UnitSandwormDataCollection.Count; }
        }

        public void Clear()
		{
			UnitSandwormDataCollection.Clear();
        }

		public YAD2Configuration.UnitSandwormData Remove(int index) 
		{ 
            YAD2Configuration.UnitSandwormData obj = UnitSandwormDataCollection[index];
            UnitSandwormDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            UnitSandwormDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.UnitSandwormData),ElementName="UnitSandwormData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public UnitSandwormDataCollection __UnitSandwormDataCollection;
		
		[XmlIgnore]
		public UnitSandwormDataCollection UnitSandwormDataCollection
		{
			get
			{
				if (__UnitSandwormDataCollection == null) __UnitSandwormDataCollection = new UnitSandwormDataCollection();
				return __UnitSandwormDataCollection;
			}
			set {__UnitSandwormDataCollection = value;}
		}

		public UnitSandwormsData()
		{
		}
	}


	[XmlType(TypeName="BuildingsData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class BuildingsData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return BuildingDataCollection.GetEnumerator();
		}

		public YAD2Configuration.BuildingData Add(YAD2Configuration.BuildingData obj)
		{
			return BuildingDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.BuildingData this[int index]
		{
			get { return (YAD2Configuration.BuildingData) BuildingDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return BuildingDataCollection.Count; }
        }

        public void Clear()
		{
			BuildingDataCollection.Clear();
        }

		public YAD2Configuration.BuildingData Remove(int index) 
		{ 
            YAD2Configuration.BuildingData obj = BuildingDataCollection[index];
            BuildingDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            BuildingDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.BuildingData),ElementName="BuildingData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public BuildingDataCollection __BuildingDataCollection;
		
		[XmlIgnore]
		public BuildingDataCollection BuildingDataCollection
		{
			get
			{
				if (__BuildingDataCollection == null) __BuildingDataCollection = new BuildingDataCollection();
				return __BuildingDataCollection;
			}
			set {__BuildingDataCollection = value;}
		}

		public BuildingsData()
		{
		}
	}


	[XmlType(TypeName="AmmosData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class AmmosData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return AmmoDataCollection.GetEnumerator();
		}

		public YAD2Configuration.AmmoData Add(YAD2Configuration.AmmoData obj)
		{
			return AmmoDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.AmmoData this[int index]
		{
			get { return (YAD2Configuration.AmmoData) AmmoDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return AmmoDataCollection.Count; }
        }

        public void Clear()
		{
			AmmoDataCollection.Clear();
        }

		public YAD2Configuration.AmmoData Remove(int index) 
		{ 
            YAD2Configuration.AmmoData obj = AmmoDataCollection[index];
            AmmoDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            AmmoDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.AmmoData),ElementName="AmmoData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AmmoDataCollection __AmmoDataCollection;
		
		[XmlIgnore]
		public AmmoDataCollection AmmoDataCollection
		{
			get
			{
				if (__AmmoDataCollection == null) __AmmoDataCollection = new AmmoDataCollection();
				return __AmmoDataCollection;
			}
			set {__AmmoDataCollection = value;}
		}

		public AmmosData()
		{
		}
	}


	[XmlType(TypeName="RacesData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class RacesData
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return RaceDataCollection.GetEnumerator();
		}

		public YAD2Configuration.RaceData Add(YAD2Configuration.RaceData obj)
		{
			return RaceDataCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.RaceData this[int index]
		{
			get { return (YAD2Configuration.RaceData) RaceDataCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return RaceDataCollection.Count; }
        }

        public void Clear()
		{
			RaceDataCollection.Clear();
        }

		public YAD2Configuration.RaceData Remove(int index) 
		{ 
            YAD2Configuration.RaceData obj = RaceDataCollection[index];
            RaceDataCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            RaceDataCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.RaceData),ElementName="RaceData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public RaceDataCollection __RaceDataCollection;
		
		[XmlIgnore]
		public RaceDataCollection RaceDataCollection
		{
			get
			{
				if (__RaceDataCollection == null) __RaceDataCollection = new RaceDataCollection();
				return __RaceDataCollection;
			}
			set {__RaceDataCollection = value;}
		}

		public RacesData()
		{
		}
	}


	[XmlType(TypeName="TechnologyDependences",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class TechnologyDependences
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return TechnologyDependenceCollection.GetEnumerator();
		}

		public YAD2Configuration.TechnologyDependence Add(YAD2Configuration.TechnologyDependence obj)
		{
			return TechnologyDependenceCollection.Add(obj);
		}

		[XmlIgnore]
		public YAD2Configuration.TechnologyDependence this[int index]
		{
			get { return (YAD2Configuration.TechnologyDependence) TechnologyDependenceCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return TechnologyDependenceCollection.Count; }
        }

        public void Clear()
		{
			TechnologyDependenceCollection.Clear();
        }

		public YAD2Configuration.TechnologyDependence Remove(int index) 
		{ 
            YAD2Configuration.TechnologyDependence obj = TechnologyDependenceCollection[index];
            TechnologyDependenceCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            TechnologyDependenceCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(YAD2Configuration.TechnologyDependence),ElementName="TechnologyDependence",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public TechnologyDependenceCollection __TechnologyDependenceCollection;
		
		[XmlIgnore]
		public TechnologyDependenceCollection TechnologyDependenceCollection
		{
			get
			{
				if (__TechnologyDependenceCollection == null) __TechnologyDependenceCollection = new TechnologyDependenceCollection();
				return __TechnologyDependenceCollection;
			}
			set {__TechnologyDependenceCollection = value;}
		}

		public TechnologyDependences()
		{
		}
	}


	[XmlType(TypeName="TechnologyDependence",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class TechnologyDependence
	{

		[XmlElement(Type=typeof(string),ElementName="BuildingName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public BuildingNameCollection __BuildingNameCollection;
		
		[XmlIgnore]
		public BuildingNameCollection BuildingNameCollection
		{
			get
			{
				if (__BuildingNameCollection == null) __BuildingNameCollection = new BuildingNameCollection();
				return __BuildingNameCollection;
			}
			set {__BuildingNameCollection = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.BuildingsNames),ElementName="RequiredBuildings",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public BuildingsNamesCollection __RequiredBuildingsCollection;
		
		[XmlIgnore]
		public BuildingsNamesCollection RequiredBuildingsCollection
		{
			get
			{
				if (__RequiredBuildingsCollection == null) __RequiredBuildingsCollection = new BuildingsNamesCollection();
				return __RequiredBuildingsCollection;
			}
			set {__RequiredBuildingsCollection = value;}
		}

		public TechnologyDependence()
		{
		}
	}


	[XmlType(TypeName="BuildingsNames",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class BuildingsNames
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return NameCollection.GetEnumerator();
		}

		public string Add(string obj)
		{
			return NameCollection.Add(obj);
		}

		[XmlIgnore]
		public string this[int index]
		{
			get { return (string) NameCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return NameCollection.Count; }
        }

        public void Clear()
		{
			NameCollection.Clear();
        }

		public string Remove(int index) 
		{ 
            string obj = NameCollection[index];
            NameCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            NameCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(string),ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public NameCollection __NameCollection;
		
		[XmlIgnore]
		public NameCollection NameCollection
		{
			get
			{
				if (__NameCollection == null) __NameCollection = new NameCollection();
				return __NameCollection;
			}
			set {__NameCollection = value;}
		}

		public BuildingsNames()
		{
		}
	}


	[XmlType(TypeName="Size",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class Size
	{

		[XmlElement(ElementName="X",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __X;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __XSpecified;
		
		[XmlIgnore]
		public int X
		{ 
			get { return __X; }
			set { __X = value; __XSpecified = true; }
		}

		[XmlElement(ElementName="Y",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __Y;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __YSpecified;
		
		[XmlIgnore]
		public int Y
		{ 
			get { return __Y; }
			set { __Y = value; __YSpecified = true; }
		}

		public Size()
		{
		}
	}


	[XmlType(TypeName="RideableFields",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class RideableFields
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return indexCollection.GetEnumerator();
		}

		public int Add(int obj)
		{
			return indexCollection.Add(obj);
		}

		[XmlIgnore]
		public int this[int index]
		{
			get { return (int) indexCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return indexCollection.Count; }
        }

        public void Clear()
		{
			indexCollection.Clear();
        }

		public int Remove(int index) 
		{ 
            int obj = indexCollection[index];
            indexCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            indexCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(int),ElementName="index",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public indexCollection __indexCollection;
		
		[XmlIgnore]
		public indexCollection indexCollection
		{
			get
			{
				if (__indexCollection == null) __indexCollection = new indexCollection();
				return __indexCollection;
			}
			set {__indexCollection = value;}
		}

		public RideableFields()
		{
		}
	}


	[XmlType(TypeName="UnitsNames",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class UnitsNames
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return NameCollection.GetEnumerator();
		}

		public string Add(string obj)
		{
			return NameCollection.Add(obj);
		}

		[XmlIgnore]
		public string this[int index]
		{
			get { return (string) NameCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return NameCollection.Count; }
        }

        public void Clear()
		{
			NameCollection.Clear();
        }

		public string Remove(int index) 
		{ 
            string obj = NameCollection[index];
            NameCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            NameCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(string),ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public NameCollection __NameCollection;
		
		[XmlIgnore]
		public NameCollection NameCollection
		{
			get
			{
				if (__NameCollection == null) __NameCollection = new NameCollection();
				return __NameCollection;
			}
			set {__NameCollection = value;}
		}

		public UnitsNames()
		{
		}
	}


	[XmlRoot(ElementName="GameSettings",Namespace=Declarations.SchemaVersion,IsNullable=false),Serializable]
	[XmlType(TypeName="GameSettings",Namespace=Declarations.SchemaVersion)]
	public class GameSettings
	{

		[XmlElement(Type=typeof(YAD2Configuration.UnitTroopersData),ElementName="UnitTroopersData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.UnitTroopersData __UnitTroopersData;
		
		[XmlIgnore]
		public YAD2Configuration.UnitTroopersData UnitTroopersData
		{
			get
			{
				if (__UnitTroopersData == null) __UnitTroopersData = new YAD2Configuration.UnitTroopersData();		
				return __UnitTroopersData;
			}
			set {__UnitTroopersData = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.UnitTanksData),ElementName="UnitTanksData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.UnitTanksData __UnitTanksData;
		
		[XmlIgnore]
		public YAD2Configuration.UnitTanksData UnitTanksData
		{
			get
			{
				if (__UnitTanksData == null) __UnitTanksData = new YAD2Configuration.UnitTanksData();		
				return __UnitTanksData;
			}
			set {__UnitTanksData = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.UnitHarvestersData),ElementName="UnitHarvestersData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.UnitHarvestersData __UnitHarvestersData;
		
		[XmlIgnore]
		public YAD2Configuration.UnitHarvestersData UnitHarvestersData
		{
			get
			{
				if (__UnitHarvestersData == null) __UnitHarvestersData = new YAD2Configuration.UnitHarvestersData();		
				return __UnitHarvestersData;
			}
			set {__UnitHarvestersData = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.UnitMCVsData),ElementName="UnitMCVsData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.UnitMCVsData __UnitMCVsData;
		
		[XmlIgnore]
		public YAD2Configuration.UnitMCVsData UnitMCVsData
		{
			get
			{
				if (__UnitMCVsData == null) __UnitMCVsData = new YAD2Configuration.UnitMCVsData();		
				return __UnitMCVsData;
			}
			set {__UnitMCVsData = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.UnitSandwormsData),ElementName="UnitSandwormsData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.UnitSandwormsData __UnitSandwormsData;
		
		[XmlIgnore]
		public YAD2Configuration.UnitSandwormsData UnitSandwormsData
		{
			get
			{
				if (__UnitSandwormsData == null) __UnitSandwormsData = new YAD2Configuration.UnitSandwormsData();		
				return __UnitSandwormsData;
			}
			set {__UnitSandwormsData = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.AmmosData),ElementName="AmmosData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.AmmosData __AmmosData;
		
		[XmlIgnore]
		public YAD2Configuration.AmmosData AmmosData
		{
			get
			{
				if (__AmmosData == null) __AmmosData = new YAD2Configuration.AmmosData();		
				return __AmmosData;
			}
			set {__AmmosData = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.BuildingsData),ElementName="BuildingsData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.BuildingsData __BuildingsData;
		
		[XmlIgnore]
		public YAD2Configuration.BuildingsData BuildingsData
		{
			get
			{
				if (__BuildingsData == null) __BuildingsData = new YAD2Configuration.BuildingsData();		
				return __BuildingsData;
			}
			set {__BuildingsData = value;}
		}

		[XmlElement(Type=typeof(YAD2Configuration.RacesData),ElementName="RacesData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public YAD2Configuration.RacesData __RacesData;
		
		[XmlIgnore]
		public YAD2Configuration.RacesData RacesData
		{
			get
			{
				if (__RacesData == null) __RacesData = new YAD2Configuration.RacesData();		
				return __RacesData;
			}
			set {__RacesData = value;}
		}

		public GameSettings()
		{
		}
	}
}
